name: test

on:
  push:
    branches:
      - master
      - ci
  pull_request:
    branches:
      - master
      - ci

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, beta, nightly, 1.58.1]
    steps:
      - uses: actions/checkout@v3

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Build tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-run

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install minimal toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          components: clippy

      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install minimal toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          components: rustfmt

      - name: Run rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all --check

  codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Check coverage
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: 0.22.0
          args: --ignore-tests --workspace -- --test-threads 1

      # pull-request steps
      - name: Create report
        uses: irongut/CodeCoverageSummary@v1.3.0
        if: github.event_name == 'pull_request'
        with:
          filename: cobertura.xml
          badge: true
          format: markdown
          hide_branch_rate: true
          hide_complexity: true
          indicators: true
          output: both
          thresholds: "50 75"

      - name: Add coverage PR comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: cobertura.xml

      # push steps
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3
        if: github.event_name == 'push'
        with:
          files: cobertura.xml

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        if: github.event_name == 'push'
        with:
          name: code-coverage-report
          path: cobertura.xml
